version: "3.9"

services:
  api:
    image: "registry.evist0.me/api:latest"
    restart: unless-stopped
    ports:
      - "4000:4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-evist0.rule=Host(`api.${DOMAIN}`)"
      - "traefik.http.routers.api-evist0.entrypoints=websecure"
      - "traefik.http.routers.api-evist0.tls.certresolver=myresolver"
      - "traefik.http.routers.api-evist0.service=api-evist0"
      - "traefik.http.services.api-evist0.loadbalancer.server.port=4000"
      - "traefik.http.routers.api-evist0.middlewares=traefik-compress"
  blog:
    image: "registry.evist0.me/blog:latest"
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog-evist0.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.blog-evist0.entrypoints=websecure"
      - "traefik.http.routers.blog-evist0.tls.certresolver=myresolver"
      - "traefik.http.routers.blog-evist0.service=blog-evist0"
      - "traefik.http.services.blog-evist0.loadbalancer.server.port=3000"
      - "traefik.http.routers.blog-evist0.middlewares=traefik-compress"
  backoffice:
    image: "registry.evist0.me/backoffice:latest"
    restart: unless-stopped
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backoffice-evist0.rule=Host(`backoffice.${DOMAIN}`)"
      - "traefik.http.routers.backoffice-evist0.entrypoints=websecure"
      - "traefik.http.routers.backoffice-evist0.tls.certresolver=myresolver"
      - "traefik.http.routers.backoffice-evist0.service=backoffice-evist0"
      - "traefik.http.services.backoffice-evist0.loadbalancer.server.port=3001"
      - "traefik.http.routers.backoffice-evist0.middlewares=traefik-compress"
