name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/api
          push: true
          tags: registry.evist0.me/api:latest

  backoffice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/backoffice
          push: true
          tags: registry.evist0.me/backoffice:latest


  blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/blog
          push: true
          tags: registry.evist0.me/blog:latest

  deploy:
    needs: [ api, backoffice, blog ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DOMAIN: ${{ secrets.DOMAIN }}
          file_name: .env

      - name: Uploading .env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          source: ./.env
          target: ./
          overwrite: true

      - name: Uploading docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          source: ./docker-compose.yml
          target: ./
          overwrite: true

      - name: Pull images from GitHub Container Registry
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker compose pull

      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker compose up -d

      - name: Prune old images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker image prune -a --force
