name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  api:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.evist0.me
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/api
          push: true
          tags: registry.evist0.me/api:latest

  backoffice:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://backoffice.evist0.me
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/backoffice
          push: true
          tags: registry.evist0.me/backoffice:latest

  blog:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://evist0.me
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/blog
          push: true
          tags: registry.evist0.me/blog:latest

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://evist0.me
    needs: [ api, backoffice, blog ]

    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DOMAIN: ${{ secrets.DOMAIN }}
          envkey_TRAEFIK_PILOT_TOKEN: ${{ secrets.TRAEFIK_PILOT_TOKEN }}
          envkey_TRAEFIK_USER: ${{ secrets.TRAEFIK_USER }}
          envkey_TRAEFIK_PASSWORD: ${{ secrets.TRAEFIK_PASSWORD }}
          envkey_LETS_ENCRYPT_EMAIL: ${{ secrets.LETS_ENCRYPT_EMAIL }}
          file_name: .env

      - name: Uploading .env
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          source: ./.env
          target: ./
          overwrite: true

      - name: Uploading docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          source: ./docker-compose.yml
          target: ./
          overwrite: true

      - name: Pull images from GitHub Container Registry
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker compose pull

      - name: Docker Compose Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

      - name: Prune old images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: docker image prune -a --force
