name: CD

on:
  push:
    branches:
      - 'main'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/api
          push: true
          tags: registry.evist0.me/api:latest

  backoffice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/backoffice
          push: true
          tags: registry.evist0.me/backoffice:latest


  blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'master'
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.evist0.me
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push image
        uses: docker/build-push-action@v2
        with:
          context: ./app/blog
          push: true
          tags: registry.evist0.me/blog:latest

  deploy:
    needs: [api, backoffice, blog]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            cd ${{ secrets.HOST_PATH }}
            echo $REGISTRY_PASSWORD | sudo docker login registry.evist0.me -u $REGISTRY_LOGIN --password-stdin
            docker compose pull
            docker compose up -d
            docker image prune -a --force
          envs: REGISTRY_LOGIN, REGISTRY_PASSWORD
        env:
          REGISTRY_LOGIN: ${{ secrets.REGISTRY_LOGIN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
